# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userName',
            field=models.CharField(max_length=20),
        ),
    ]
