# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170616_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='userName',
            new_name='username',
        ),
    ]
