# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_detail',
        ),
    ]
